const SOCKECT_OPTIONS = {
  cors: {
    origin: "http://localhost:3000",
    methods: ["GET", "POST"],
  },
};
const emit = {
  USER_JOIN_CHAT: "USER_JOIN_CHAT",
  RECEIVE_PRIVATE_SINGLE_MESSAGE: "RECEIVE_PRIVATE_SINGLE_MESSAGE",
  SEND_PRIVATE_SINGLE_MESSAGE: "SEND_PRIVATE_SINGLE_MESSAGE",
  SEND_PRIVATE_GROUP_MESSAGE: "SEND_PRIVATE_GROUP_MESSAGE",
  TYPING_MESSAGE_GROUP: "TYPING_MESSAGE_GROUP",
  USER_TYPING_MESSAGE_GROUP: "USER_TYPING_MESSAGE_GROUP",
  DISPATCH_GROUP_MESSAGE: "DISPATCH_GROUP_MESSAGE",
  USER_LEAVE_CHAT: "USER_LEAVE_CHAT",
};
const rgxName = /^[a-z]{4,8}$/;
const rgxPassword = /^[a-z0-9]{5,10}$/;
module.exports = { SOCKECT_OPTIONS, rgxName, rgxPassword, emit };
